## Cours suivi par : MPOUAVOULI Rayde Prosperin
## Chapitre 1 : Maitriser la préparation des données financières

### L'objectif de ce chapitre est de noud permettre :
###### - Importer des données financières depuis differentes sources( yahoo finance, CSV)
###### - Nettoyage des données
###### - Gérer les formats de date et de manipuler les fréquences
###### - De verifier la qualité globale d'un dataset financier 
###### - D'appliquer ces compétences sur des cas concrets

#### 1- Importer les données boursières

In [9]:
pip install yfinance

Requirement already satisfied: yfinance in c:\programdata\anaconda3\lib\site-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.7 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\programdata\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import yfinance as yf
import pandas as pd

In [13]:
## téléchargement des données de Apple 
apple = yf.download("AAPL", start = "2020-01-01", end ="2024-12-31")

C:\Users\Visiteur\AppData\Local\Temp\ipykernel_67596\3825187713.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  apple = yf.download("AAPL", start = "2020-01-01", end ="2024-12-31")
[*********************100%***********************]  1 of 1 completed

In [14]:
apple.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.538513  72.598892  71.292304  71.545890  135480400
2020-01-03  71.833298  72.594063  71.608692  71.765674  146322800
2020-01-06  72.405685  72.444328  70.703020  70.954195  118387200
2020-01-07  72.065163  72.671356  71.845385  72.415353  108872000
2020-01-08  73.224403  73.526295  71.768079  71.768079  132079200

In [15]:
apple.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1257 entries, 2020-01-02 to 2024-12-30
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   1257 non-null   float64
 1   (High, AAPL)    1257 non-null   float64
 2   (Low, AAPL)     1257 non-null   float64
 3   (Open, AAPL)    1257 non-null   float64
 4   (Volume, AAPL)  1257 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.9 KB

In [16]:
# supprimer le niveau ticker qui n'est pas assez important
apple.columns = apple.columns.droplevel("Ticker")

In [17]:
apple.head()

Price           Close       High        Low       Open     Volume
Date
2020-01-02  72.538513  72.598892  71.292304  71.545890  135480400
2020-01-03  71.833298  72.594063  71.608692  71.765674  146322800
2020-01-06  72.405685  72.444328  70.703020  70.954195  118387200
2020-01-07  72.065163  72.671356  71.845385  72.415353  108872000
2020-01-08  73.224403  73.526295  71.768079  71.768079  132079200

In [21]:
print(apple.shape) # afficher le nombre de lignes et de colonne
print(apple.index) # Afficher l'index de la dateaframe
print(apple.size) # Afficher le nombre total d'élements du DtataFrame

(1257, 5)
DatetimeIndex(['2020-01-02', '2020-01-03', '2020-01-06', '2020-01-07',
               '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-13',
               '2020-01-14', '2020-01-15',
               ...
               '2024-12-16', '2024-12-17', '2024-12-18', '2024-12-19',
               '2024-12-20', '2024-12-23', '2024-12-24', '2024-12-26',
               '2024-12-27', '2024-12-30'],
              dtype='datetime64[ns]', name='Date', length=1257, freq=None)
6285

In [24]:
# Données historiques d'APPLE et de TESLA
apple_tesla = yf.download(["AAPL", "TSLA"], start ="2020-01-01", end ="2024-12-31", group_by ="ticker")
apple_tesla.head()

C:\Users\Visiteur\AppData\Local\Temp\ipykernel_67596\2278861924.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  apple_tesla = yf.download(["AAPL", "TSLA"], start ="2020-01-01", end ="2024-12-31", group_by ="ticker")
[*********************100%***********************]  2 of 2 completed

Ticker           AAPL                                                   TSLA  \
Price            Open       High        Low      Close     Volume       Open
Date
2020-01-02  71.545890  72.598892  71.292304  72.538513  135480400  28.299999
2020-01-03  71.765674  72.594063  71.608692  71.833298  146322800  29.366667
2020-01-06  70.954195  72.444328  70.703020  72.405685  118387200  29.364668
2020-01-07  72.415353  72.671356  71.845385  72.065163  108872000  30.760000
2020-01-08  71.768079  73.526295  71.768079  73.224403  132079200  31.580000

Ticker
Price            High        Low      Close     Volume
Date
2020-01-02  28.713333  28.114000  28.684000  142981500
2020-01-03  30.266666  29.128000  29.534000  266677500
2020-01-06  30.104000  29.333332  30.102667  151995000
2020-01-07  31.441999  30.224001  31.270666  268231500
2020-01-08  33.232666  31.215334  32.809334  467164500

In [26]:
tsla = apple_tesla["TSLA"]
apple = apple_tesla["AAPL"]

In [27]:
tsla.head()

Price            Open       High        Low      Close     Volume
Date
2020-01-02  28.299999  28.713333  28.114000  28.684000  142981500
2020-01-03  29.366667  30.266666  29.128000  29.534000  266677500
2020-01-06  29.364668  30.104000  29.333332  30.102667  151995000
2020-01-07  30.760000  31.441999  30.224001  31.270666  268231500
2020-01-08  31.580000  33.232666  31.215334  32.809334  467164500

In [28]:
apple.head()

Price            Open       High        Low      Close     Volume
Date
2020-01-02  71.545890  72.598892  71.292304  72.538513  135480400
2020-01-03  71.765674  72.594063  71.608692  71.833298  146322800
2020-01-06  70.954195  72.444328  70.703020  72.405685  118387200
2020-01-07  72.415353  72.671356  71.845385  72.065163  108872000
2020-01-08  71.768079  73.526295  71.768079  73.224403  132079200

In [29]:
apple.head(10)

Price            Open       High        Low      Close     Volume
Date
2020-01-02  71.545890  72.598892  71.292304  72.538513  135480400
2020-01-03  71.765674  72.594063  71.608692  71.833298  146322800
2020-01-06  70.954195  72.444328  70.703020  72.405685  118387200
2020-01-07  72.415353  72.671356  71.845385  72.065163  108872000
2020-01-08  71.768079  73.526295  71.768079  73.224403  132079200
2020-01-09  74.202512  74.972939  73.951343  74.779732  170108400
2020-01-10  75.014012  75.513947  74.446455  74.948799  140644800
2020-01-13  75.265196  76.576611  75.146850  76.550041  121532000
2020-01-14  76.487261  76.697376  75.393206  75.516373  161954400
2020-01-15  75.315916  76.197437  74.760431  75.192741  121923600

#### Nettoyer les données

In [31]:
# Identifier les valeurs manquantes
apple.isnull().sum()

Price
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [32]:
apple.isnull().mean()

Price
Open      0.0
High      0.0
Low       0.0
Close     0.0
Volume    0.0
dtype: float64

In [36]:
# Verification des doublants
apple.duplicated().sum()

np.int64(0)

In [37]:
# traiter les valeurs manquantes
## Supprimer les valeurs manquantes
apple_clean =apple.dropna()

In [38]:
apple_clean.head()

Price            Open       High        Low      Close     Volume
Date
2020-01-02  71.545890  72.598892  71.292304  72.538513  135480400
2020-01-03  71.765674  72.594063  71.608692  71.833298  146322800
2020-01-06  70.954195  72.444328  70.703020  72.405685  118387200
2020-01-07  72.415353  72.671356  71.845385  72.065163  108872000
2020-01-08  71.768079  73.526295  71.768079  73.224403  132079200

In [41]:
# Supprimer les doublants
apple_clean = apple_clean.drop_duplicates()

#### 3- Gérer les dates et les fréquences

In [42]:
apple_clean.index

DatetimeIndex(['2020-01-02', '2020-01-03', '2020-01-06', '2020-01-07',
               '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-13',
               '2020-01-14', '2020-01-15',
               ...
               '2024-12-16', '2024-12-17', '2024-12-18', '2024-12-19',
               '2024-12-20', '2024-12-23', '2024-12-24', '2024-12-26',
               '2024-12-27', '2024-12-30'],
              dtype='datetime64[ns]', name='Date', length=1257, freq=None)

In [45]:
apple_clean.index = pd.to_datetime(apple_clean.index) #Convertir en format date

In [46]:
type(apple_clean.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [48]:
# transformer les valeurs en fréquence journalière 
weekly_date = apple_clean.resample("w").mean() # Transformer des données journalières en données hebdomadaires

C:\Users\Visiteur\AppData\Local\Temp\ipykernel_67596\2022622159.py:2: FutureWarning: 'w' is deprecated and will be removed in a future version, please use 'W' instead.
  weekly_date = apple_clean.resample("w").mean()

In [49]:
weekly_date.head()

Price            Open       High        Low      Close       Volume
Date
2020-01-05  71.655782  72.596477  71.450498  72.185905  140901600.0
2020-01-12  72.870830  73.825773  72.542856  73.484756  134018320.0
2020-01-19  75.837582  76.539419  75.350207  76.074263  130411120.0
2020-01-26  76.918363  77.398972  76.467939  76.789759  115921300.0
2020-02-02  76.732631  77.515615  75.617322  76.528793  173346960.0

In [51]:
monthly_date = apple_clean.resample("ME").mean()# Transformer des données journalières en données mensuelles

In [52]:
monthly_date.head()

Price            Open       High        Low      Close        Volume
Date
2020-01-31  75.151916  75.913947  74.586890  75.331900  1.397319e+08
2020-02-29  75.084558  76.279686  74.216426  75.315940  1.589094e+08
2020-03-31  63.202393  65.288957  61.694853  63.534161  2.854578e+08
2020-04-30  65.801869  66.762953  64.899579  65.941011  1.554904e+08
2020-05-31  74.931114  75.990009  74.323386  75.197802  1.402968e+08

In [54]:
quartely_date = apple_clean.resample("QE").mean()# Transformer des données journalières en données trimestrielles
quartely_date.head()

Price             Open        High         Low       Close        Volume
Date
2020-03-31   70.891121   72.255870   69.898767   71.140715  1.973181e+08
2020-06-30   74.927340   75.991048   74.103171   75.165613  1.478510e+08
2020-09-30  106.218467  107.742450  104.267742  106.068825  1.714936e+08
2020-12-31  117.146026  118.604253  115.666118  117.122528  1.146865e+08
2021-03-31  125.433437  126.857689  123.534233  125.185209  1.102383e+08

In [55]:
yearly_date = apple_clean.resample("YE").mean()# Transformer des données journalières en données annuelles
yearly_date.head()

Price             Open        High         Low       Close        Volume
Date
2020-12-31   92.533595   93.887308   91.217353   92.610295  1.575646e+08
2021-12-31  137.731617  139.184621  136.375163  137.856632  9.052463e+07
2022-12-31  152.203232  154.272926  150.127144  152.234924  8.791038e+07
2023-12-31  170.387286  171.970139  169.126459  170.676110  5.922355e+07
2024-12-31  205.603920  207.555331  203.883046  205.865363  5.717700e+07

In [58]:
### controler la cohérence et filtrer des données
#selection des olonnes pertinentes
data_filered = apple[["Open", "Close", "Volume"]]
data_filered.head(5)

Price            Open      Close     Volume
Date
2020-01-02  71.545890  72.538513  135480400
2020-01-03  71.765674  71.833298  146322800
2020-01-06  70.954195  72.405685  118387200
2020-01-07  72.415353  72.065163  108872000
2020-01-08  71.768079  73.224403  132079200

In [62]:
cols =["Open", "Close", "Volume"]
data_filered = apple[cols]
data_filered.head()

Price            Open      Close     Volume
Date
2020-01-02  71.545890  72.538513  135480400
2020-01-03  71.765674  71.833298  146322800
2020-01-06  70.954195  72.405685  118387200
2020-01-07  72.415353  72.065163  108872000
2020-01-08  71.768079  73.224403  132079200

In [66]:
# Conserver les données entre mars 2024 et septembre 2024
data_filered = apple.loc["2024-03-01":"2024-09-01"]
data_filered.head()

Price             Open        High         Low       Close    Volume
Date
2024-03-01  178.269827  179.242836  176.115301  178.379044  73563100
2024-03-04  174.894049  175.638701  172.550875  173.851547  81510100
2024-03-05  169.542464  170.813337  168.410593  168.907028  95132400
2024-03-06  169.840355  170.019079  167.477319  167.914185  68587700
2024-03-07  167.943968  169.512705  167.288686  167.795044  71765100

In [67]:
# Conserver les dates par lesquelles la valeur de cloture est superieure à 2025
data_filered = apple[apple["Close"] > 250]

In [69]:
apple["Close"] > 250

Date
2020-01-02    False
2020-01-03    False
2020-01-06    False
2020-01-07    False
2020-01-08    False
              ...
2024-12-23     True
2024-12-24     True
2024-12-26     True
2024-12-27     True
2024-12-30     True
Name: Close, Length: 1257, dtype: bool

In [70]:
data_filered.describe()

Price        Open        High         Low       Close        Volume
count    8.000000    8.000000    8.000000    8.000000  8.000000e+00
mean   252.182262  254.891397  250.772267  254.009525  5.247374e+07
std      4.097646    2.967427    3.951276    2.738020  3.972443e+07
min    247.112764  250.490771  244.820894  250.151962  2.323470e+07
25%    248.687175  252.849900  248.365815  252.264473  3.347740e+07
50%    252.603271  254.421812  251.013906  253.978394  4.160705e+07
75%    255.169157  257.418667  253.011819  255.336063  5.144100e+07
max    257.276679  259.179926  256.718662  258.103729  1.474953e+08

### Echantillonner les données

In [72]:
# uniformiser
apple_clean["Volume"] = apple_clean["Volume"]/1000
apple_clean["Volume"].describe()

count    1257.000000
mean       90.611679
std        53.246046
min        23.234700
25%        55.469600
50%        76.299700
75%       107.760100
max       426.510000
Name: Volume, dtype: float64

In [80]:
# prendre un échantillon de 20% aléatoirement pour tester des annalyses
sample = apple_clean.sample(frac=0.2)
sample.describe()

Price        Open        High         Low       Close      Volume
count  251.000000  251.000000  251.000000  251.000000  251.000000
mean   151.390007  153.030179  149.825851  151.508150   88.057012
std     38.367340   38.615043   38.141842   38.388531   47.846906
min     55.215083   55.316759   51.470005   54.316940   31.458200
25%    130.710609  131.460460  128.185190  129.934708   55.207300
50%    150.000525  151.566747  148.250631  149.619888   76.299700
75%    174.684034  175.485476  172.112047  173.941032  102.857000
max    256.917934  257.784882  252.164818  254.685867  336.752800

In [81]:
# Por fixer les aléa
sample = apple_clean.sample(frac=0.2, random_state=255)
sample.describe()

Price        Open        High         Low       Close      Volume
count  251.000000  251.000000  251.000000  251.000000  251.000000
mean   153.282053  154.935485  151.740061  153.455942   89.556594
std     41.456457   41.668534   41.296238   41.750269   57.843454
min     59.674311   60.211743   55.195714   55.495903   35.169600
25%    126.561867  128.201263  125.458217  127.714581   53.949400
50%    152.670065  154.361657  151.213062  153.395447   74.602000
75%    178.333247  179.704808  177.060708  178.699661  104.117950
max    253.868788  254.745665  252.553450  254.367020  426.510000

In [82]:
# On peut faire l'échantillonnage en fonction du nombre d'observation
# Echantillon
sample = apple_clean.sample(n=200, random_state=255)
sample.describe()

Price        Open        High         Low       Close      Volume
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   154.341786  156.040045  152.842964  154.573125   91.354077
std     42.347195   42.573616   42.262004   42.727423   62.744670
min     59.674311   60.211743   55.195714   55.495903   35.169600
25%    126.919252  128.888223  126.274433  128.057610   53.229025
50%    152.542071  154.298488  151.217968  152.737389   74.277250
75%    183.618493  185.042371  182.487491  184.502754  102.251700
max    253.868788  254.745665  252.553450  254.367020  426.510000